### ISSUE TITLE
[BUG] Position score resource test hanging

### ISSUE THREAD

**Issue by IvoTod** [iossifovlab/gpf#272]
**What happened**:
I updated a position score resource configuration used for tests and forgot to run repair-resource. I then ran the tests and this specific [test](https://github.com/iossifovlab/gpf/blob/master/dae/dae/genomic_resources/tests/test_position_score.py#L155) hangs **after failing** because it starts a MotoServer which does not shut down properly.
**What you expected to happen**:
The servers that the test runs should close when the test fails successfully.
**Steps to reproduce**:

1. Edit `dae_conftests/dae_conftests/tests/fixtures/genomic_resources/hg38/TESTphastCons100way/genomic_resource.yaml` (e.g. add a "# delete" at the bottom of the file) without repairing the resource
2. Go to `dae/dae/genomic_resources/tests` and run `pytest test_position_score.py::test_position_score_over_http`

**Anything else we need to know?**:
I tested if this behavior happens if the test fails normally by adding an `assert False` after the server is ran and the server closes normally. I believe this strange behavior seems to have something to do with the IOError that gets raised [here](https://github.com/iossifovlab/gpf/blob/master/dae/dae/genomic_resources/fsspec_protocol.py#L427) when the manifest of the resource is outdated.

**Comment by iordanivanov** [comment]
There is another test that can hang - `dae/dae/genomic_resources/tests/test_range_http_server.py::test_process_server_simple`.

It hangs if you request the 'hg19/CADD' resource - currently I have set it to get the 'hg19/MPC' resource so that it doesn't hang. The problem comes when you open the CADD resource - the whole HTTP server seems to block afterwards. If you do not request the CADD resource, everything is fine - you can download CADD via curl or the browser.
